invoice:
  template: invoice.html
  prefix: Invoice_
  defaultVat: 0.21
  locale: en-GB
  paymentTerm: 14
  outDir:

company:
  name:
  address:
  zipcode:
  city:
  vatId:
  coc:
  accountHolder:
  iban:
  phone:
  email:

clients:
  - id: 1
    company:
    contact:
    address:
    zipcode:
    city:
    country:
    vatId:

  - id: 2
    company:
    contact:
    address:
    zipcode:
    city:
    country:
    vatId:
