company:
  name:
  address:
  zipcode:
  city:
  vat:
  coc:
  accountHolder:
  iban:
  phone:
  email:

invoice:
  template: invoice.html
  prefix: INVOICE_
  defaultVat: 0.21
  locale: en-GB
  paymentTerm: 14
  outDir:

clients:
  - id: 1
    company:
    contact:
    adress:
    zipcode:
    city:
    country:
    vatId:

  - id: 2
    company:
    contact:
    adress:
    zipcode:
    city:
    country:
    vatId:
